# Robbie Tovar
## week 9 10/15/24
### Python numpy intro

** what is numpy?**
- numPy is a python library
- NumPy is used for workingh with arrays
- NumPy is short for numerical python 

**Why NumPy?**
- arrays are very frequently used in data science 
- spped adn resources are very important 
- 50x faster than traditional pyton lists
-

In [1]:
import numpy as np

In [4]:
np.__version__

'1.18.5'

In [6]:
#create a NumPy nd-array  object
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#dimensions in array
#a dimension in array is one level of array depth (nested arrays)
# nested arraty: are arrays that have arrays as their elements 
# 0-D arrays opr scalars 
arr_0d = np.array(50)
arr_0d

array(50)

In [11]:
arr_0d.ndim

0

In [12]:
type(arr_0d)

numpy.ndarray

In [19]:
#1-d array
# an array that has o-d arrays as its elemnts
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d, ' ndim=', arr_1d.ndim)

[1 2 3 4 5 6]  ndim= 1


In [47]:
# 2-d arrat 
# an arrat that has 1-d arrays as its elemtns 
arr_2d = np.array([ [1,2,3,4,5,6] , [7,8,9] ])
print(arr_2d, ' ndim=', arr_2d.ndim)

[list([1, 2, 3, 4, 5, 6]) list([7, 8, 9])]  ndim= 1


In [21]:
arr_2d

array([list([1, 2, 3, 4, 5, 6]), list([7, 8, 9])], dtype=object)

In [22]:
arr_2d.ndim

1

In [25]:
#3-d raary 
# an array that has 2-d arrays (metrices) as its elemnts 
arr_3d = np.array( [ [ [1,2,3], [4,5,6] ], [ [7,8,9], [10,11,12] ] ])
print(arr_3d, ' ndim=', arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]  ndim= 3


In [27]:
#cerated 4-d
arr_4d = np.array([1,2,3,4,5], ndmin=4)
arr_4d

array([[[[1, 2, 3, 4, 5]]]])

In [28]:
arr_4d.ndim

4

In [29]:
arr_3d.shape

(2, 2, 3)

In [30]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
arr_4d.shape


(1, 1, 1, 5)

In [32]:
arr_4d

array([[[[1, 2, 3, 4, 5]]]])

In [33]:
#array indexing
arr_1d

array([1, 2, 3, 4, 5, 6])

In [34]:
arr_1d.shape

(6,)

In [35]:
arr_1d[1]

2

In [36]:
arr_1d[-1]

6

In [37]:
arr_1d[0]

1

In [38]:
arr_2d

array([list([1, 2, 3, 4, 5, 6]), list([7, 8, 9])], dtype=object)

In [39]:
arr_2d.shape

(2,)

In [40]:
arr_2d[0]

[1, 2, 3, 4, 5, 6]

In [41]:
arr_2d[1]

[7, 8, 9]

In [42]:
arr_2d[0,-1]

IndexError: too many indices for array

In [43]:
arr_2d

array([list([1, 2, 3, 4, 5, 6]), list([7, 8, 9])], dtype=object)

In [45]:
arr_2d[1,0] = arr_2d[1,0] + arry_2d[0,0]

IndexError: too many indices for array