In [1]:
def f(n):
    return n * 3
print(f(4))

12


In [2]:
def f(*args):
    for i in args:
        print(i)
f(name="Emma",age=25)

TypeError: f() got an unexpected keyword argument 'name'

In [ ]:
s=set()
s.add(10)
s.add((1,2,3))
s.add('one')
s.add('{1,2,3}')
print(s)

In [ ]:
l = [1,2,3,4,5,6]
print(l[0:-2])

In [ ]:
x = "700"
print(x.isdigit())

In [ ]:
if 'bar' in['foo', 'bar', 'baz']:
    print(1)
    print(2)
    if 'a' in 'qux':
        print(3)
print(4)

In [ ]:
for x in [1,2]:
    for y in ["chairs", "Tables"]:
        print(x,y)

In [3]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ]) 
print(np.mean(a, axis=None)== np.mean(a))

True


In [6]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [7]:
x

array([[1., 0.],
       [0., 0.]])

In [8]:
y

matrix([[1., 1.],
        [2., 0.]])

In [9]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))

In [10]:
a

array([1., 1.])

In [11]:
b

array([[1., 1.]])

In [12]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [13]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [14]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [15]:
import numpy as np
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [16]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]
a

array([[ 5,  7,  3,  2,  1],
       [ 6,  4,  8,  9, 10]])

In [17]:
import numpy as np 

a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [18]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1, 0]
a[0,0]= a[0,2] + a[2,0]
a

array([[10,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  0]])

In [19]:
import numpy as np 
a = np.array([[1, 0], [2, -1]])
r = a * a

In [20]:
r

array([[1, 0],
       [4, 1]])

In [22]:
import numpy as np
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)
b

array([1, 2, 3, 4, 5, 6])

In [23]:
import numpy as np

np.random.random((2,2))

array([[0.31446899, 0.07223108],
       [0.26726135, 0.9280859 ]])

In [24]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)


In [25]:
a

array([[0., 0.],
       [0., 0.]])

In [26]:
b

array([[1., 0.],
       [0., 1.]])

In [27]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = a.T

In [28]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]

In [30]:
b

[1, 3, 2, 4]

In [31]:
import numpy as np
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]

In [32]:
b

array([[ 7,  8],
       [11, 12]])

In [36]:

import numpy as np 
a = np.matrix([[1, 0], [2, -1]])
r = a * a
r

matrix([[1, 0],
        [0, 1]])

In [34]:
r

matrix([[1, 0],
        [0, 1]])

In [37]:
import numpy as np 

b = np.mat([[5, 6], [7, 8]])

In [38]:
b

matrix([[5, 6],
        [7, 8]])

In [39]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I


In [40]:
x

array([[1., 0.],
       [0., 0.]])

In [41]:
y

matrix([[1., 1.],
        [2., 0.]])

In [42]:
import numpy as np 

a = np.zeros((2,2))

b = np.eye(2)

In [43]:
a

array([[0., 0.],
       [0., 0.]])

In [44]:
b

array([[1., 0.],
       [0., 1.]])