# Robbie Tovar
# week 12 11/5/24 
### python numpy real world exampels

In [1]:
# computing grades
import numpy as np 
from numpy.random import random

scores = np.round(random(50) * 101).astype(int)
scores

array([ 64,   8,  27,  87,  81,  51,  81,  23,  64,  88,  26,  81,  64,
        28,  53,  71,  95,   2,  76,  88,  27,  85,   7,  33,  45,  85,
        15,  63,  87,  86,  13,  49,  41,  77,  61,  46,  20,  87,  93,
        66, 100,  84,  46,  55,   5,   8,   5, 100,  44,  48])

In [2]:
np.mean(scores)

54.78

In [3]:
scores.min()

2

In [4]:
scores.max()

100

In [5]:
np.std(scores)

29.687229577715733

In [6]:
scores[scores>70]

array([ 87,  81,  81,  88,  81,  71,  95,  76,  88,  85,  85,  87,  86,
        77,  87,  93, 100,  84, 100])

In [7]:
len(scores[scores>70])

19

In [8]:
#find n largest scores 
n =10
scores.sort()
scores[-n::]

array([ 86,  87,  87,  87,  88,  88,  93,  95, 100, 100])

In [9]:
#linear regression 
# y= a+bx
x = np.array([1,2,3,4,5,6])
y = np.array([50,60,70,80,90,100])

slope, intercept = np.polyfit(x,y,1)
print(f'slope={slope}, and intercept = {intercept}')

slope=9.999999999999996, and intercept = 39.999999999999986


In [10]:
#financial calcul;ations 
#calculating the future value of an investment 
initial_investment = 10000
annual_interest_rate = .05
years = np.arange(1,11)
future_value = initial_investment * (1 + annual_interest_rate)**years
for year, value in zip(years, future_value):
    print(f'year {year}: ${value:.2f}')

year 1: $10500.00
year 2: $11025.00
year 3: $11576.25
year 4: $12155.06
year 5: $12762.82
year 6: $13400.96
year 7: $14071.00
year 8: $14774.55
year 9: $15513.28
year 10: $16288.95


In [11]:
# portfolio optimization 
returns = np.array([.07, .05]) # excpect retuersn from each asset in portfoilios
weights = np.array([.6,.4]) # weightrs of each asset in portflio
portfolio_return = np.dot(returns, weights)
print(portfolio_return)

0.062000000000000006


In [12]:
#health care
# the effectivness of treatment by comparing pateint outcomes
sample = [0,1] #1 - success, 0 failure

group1 = np.random.choice(sample, 15)
print(group1)
group2 = np.random.choice(sample, 15)
print(group2)

[1 0 0 1 1 1 0 1 1 1 0 0 0 1 0]
[1 0 0 0 1 0 1 0 0 0 0 1 0 0 1]


In [13]:
success_1 = np.mean(group1)
success_2 = np.mean(group2)
print(f'success rate for group 1 {success_1}')
print(f'success rate for group 2 {success_2}')

success rate for group 1 0.5333333333333333
success rate for group 2 0.3333333333333333


In [14]:
#scientific notation
n = np.array([10.1,10.5,9.9,10.3,10.0])

mean_measurement = np.mean(n)
std_measurement = np.std(n)

print(f'Mean: {mean_measurement} and standard devation {std_measurement}')

Mean: 10.16 and standard devation 0.2154065922853802


In [15]:
# image processing

import matplotlib.pyplot as plt

from PIL import Image


images= np.array(image.open('c://users/anaconda/downloads/python.jpg'))
print(images)
print(images.ndim)
print(images.shape)

#convert to gray scale
gray_image = np.dat(image[...:3],[0.2989,.5870,.1140])


NameError: name 'image' is not defined

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

#open image
image = np.array(Image.open('c:/users/anaconda/downloads/python.jpg'))

#print image information
print(image)
print(f'Number of dimesnsions: {image.ndim}')
print(f'Shape of the image: [image.shape]')

#Optionally, display the image
plt.imshow(image)
plt.axis('off') # hide axes for better view
plt.show()