# Robbie Tovar
## week 10 10/24/24
### python numpy - creating processing transporting arrays 

In [2]:
import numpy as np
#zeros
arr_1d = np.zeros(10)
arr_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr_2d = np.zeros((5,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
arr_1d + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
arr_2d + 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [6]:
arr = np.ones((5,5,2))
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
arr.shape

(5, 5, 2)

In [8]:
arr = np.empty((5,2))
arr

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

In [11]:
arr = np.empty(((2,2,2)), dtype=int)
arr

array([[[7471202, 7471201],
        [6029433, 7536757]],

       [[6029426, 6881378],
        [3866734, 3801187]]])

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(10,101,10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
#reshape an array
#reshape 1-d 2-d
arr_1d = np.arange(1,13,1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
arr_2d = arr_1d.reshape(2,6)

In [17]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
arr_1d[:4]=[0,0,0,0]
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
arr_1d

array([ 0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr_2d = np.arange(1,13,1).reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr_3d = np.arange(1,13,1).reshape(3,2,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
arr_3d = np.arange(1,13,1).reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
#pass -1 as the valu,e numpy will calculate this number for you
arr_3d = np.arange(1,13,1).reshape(2,-1,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [27]:
arr_3d = np.arange(1,13,1).reshape(2,2,-1)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
#reshape 3d to 1d
arr_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr_3d.reshape((-1,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
arr_2d = arr_3d.reshape((-1,3))

In [31]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
arr_2d.shape

(4, 3)

In [33]:
#integrating 1-d
for n in arr_1d:
    print(n)

0
0
0
0
5
6
7
8
9
10
11
12


In [37]:
#iterating 2-d
for n in  arr_2d:
    print(n)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [41]:
for n in arr_2d:
    for num in n:
        print(n)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[7 8 9]
[7 8 9]
[7 8 9]
[10 11 12]
[10 11 12]
[10 11 12]


In [46]:
#iterating 3d array
for n in arr_3d:
    for row in n:
        for num in row:
            print(num, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [47]:
#nditer iterates on each scalar elemtn in np array
for n in np.nditer(arr_3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
for n in np.nditer(arr_2d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [52]:
#mmultidemensional index iterator 
#ndenumerate()
for i, n in np.ndenumerate(arr_1d):
    print(i, n)

(0,) 0
(1,) 0
(2,) 0
(3,) 0
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [57]:
for i, n in np.ndenumerate(arr_2d):
    print(i, n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
(3, 0) 10
(3, 1) 11
(3, 2) 12


In [58]:
for i, n in np.ndenumerate(arr_3d):
    print(i,n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [59]:

arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr_3d[:,:,-2]

array([[ 2,  5],
       [ 8, 11]])

In [61]:
arr_3d[...,-2:]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [63]:
for n in np.nditer(arr_3d[:,:,-2]):
    print(n,end='')

25811